---
- hosts: centos,ubuntu
  tasks:
    - name: Ensure key is in root's ~/.ssh/authorized_hosts
      authorized_key:
        user: ansible
        state: present
        key: '{{ item }}'
      with_file:
        - ~/.ssh/id_rsa.pub
    
