---
- name: variables demo
  hosts: centos
  become: yes
  vars:
    web_pkg: httpd
    firewall_pkg: firewalld
    web_service: httpd
    firewall_service: firewalld
    python_pkg: uri
    rule: http
  tasks:
  - name: install apache2 and firewalld
    yum:
      name:
      - "{{web_pkg}}"
      - "{{firewall_pkg}}"
      state: latest

  - name: start apache2
    service:
      name: "{{web_service}}"
#      - "{{firewall_pkg}}"
      state: started
      enabled: yes

  - name: start firewalld 
    service:
      name: "{{firewall_service}}"
      state: started
      enabled: yes

  - name: open port 80
    firewalld:
      service: "{{rule}}"
      state: enabled
#      permanent: yes
#      immediate: yes

- name: validate url
  hosts: localhost
  tasks:
  - name: validate url
    uri:
      url: http://centosnode1
      status_code: 200
