---
- hosts: centos
  become: true
  vars:
    web_package: httpd
    db_package: mariadb-server
    db_service: mariadb
  tasks:
  - block:
    - name: install {{web_package}} 
      yum:
        name: "{{web_package}}"
        state: latest
      failed_when: web_package == "httpd"

    rescue:
    - name: install {{db_package}} 
      yum:
        name: "{{db_package}}"
        state: latest

    always:
    - name: starte {{db_service}}
      service:
        name: "{{db_service}}"
        state: started

  - name: check local time
    command: date
    register: local_time
    changed_when: false

  - name: print local time
    debug:
      var: local_time.stdout
