---
- name: copy facts file to manage hosts
  hosts: centos
  become: true
  remote_user: devops
  tasks:
  - name: create /etc/ansible/facts.d
    file:
      path: /etc/ansible/facts.d
      state: directory

  - name: create /etc/ansible/facts.d
    copy:
      src: custom.fact
      dest: /etc/ansible/facts.d/custom.fact
